name: New Problem Check

on:
  push:
    paths:
      - "utils/new_problem.yaml"
      - "utils/validate_yaml.py"
  pull_request:
      - "utils/new_problem.yaml"
      - "utils/validate_yaml.py"
  workflow_dispatch: # allow triggering workflow manually
    inputs:
      reason:
        description: "Reason for Running"
        required: false
        default: "Manually trigger problem check"

jobs:
  check_new_problems:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/requirements.txt

      - name: Run New Problem Check
        run: |
          python utils/validate_yaml.py utils/new_problem.yaml

